services:
  - type: web
    name: forest-climate-calculator
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
