services:
  - type: web
    name: forest-climate-calculator
    env: static
    buildCommand: ./build.sh
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
